spark.expectations.notifications.email.enabled: false
spark.expectations.notifications.email.smtp_server_auth: false
spark.expectations.notifications.enable.custom.email.body: false
spark.expectations.notifications.enable.templated.basic.email.body: false
spark.expectations.notifications.default.basic.email.template: ""
spark.expectations.notifications.email.smtp_host: ""
spark.expectations.notifications.email.smtp_port: 25
spark.expectations.notifications.smtp.password: ""
spark.expectations.notifications.email.from: ""
spark.expectations.notifications.email.to.other.mail.com: ""
spark.expectations.notifications.email.subject: "spark-expectations-testing"
spark.expectations.notifications.slack.enabled: false
spark.expectations.notifications.slack.webhook_url: ""
spark.expectations.notifications.teams.enabled: false
spark.expectations.notifications.teams.webhook_url: ""
spark.expectations.notifications.zoom.enabled: false
spark.expectations.notifications.zoom.webhook_url: ""
spark.expectations.notifications.zoom.token: ""
spark.expectations.notifications.on_start: false
spark.expectations.notifications.on.completion: true
spark.expectations.notifications.on.fail: true
spark.expectations.notifications.on.error.drop.exceeds.threshold.breach: false
spark.expectations.notifications.on.rules.action.if.failed.set.ignore: false
spark.expectations.notifications.error.drop.threshold: 100
spark.expectations.agg.dq.detailed.stats: false
spark.expectations.query.dq.detailed.stats: false
spark.expectations.job.metadata: None
se.streaming.enable: true
se.streaming.secret.type: "databricks"
se.streaming.dbx.workspace.url: "https://workspace.cloud.databricks.com"
se.streaming.dbx.secret.scope: "secret_scope"
se.streaming.dbx.kafka.server.url: "se_streaming_server_url_secret_key"
se.streaming.dbx.secret.token.url: "se_streaming_auth_secret_token_url_key"
se.streaming.dbx.secret.app.name: "se_streaming_auth_secret_appid_key"
se.streaming.dbx.secret.token: "se_streaming_auth_secret_token_key"
se.streaming.dbx.topic.name: "se_streaming_topic_name"
