version: '3.8'

services:
  spark-notebooks:
    build:
      context: ../
      dockerfile: containers/jupyterlab/Dockerfile.notebook
    ports:
      - "8888:8888"
    # volumes:
    #   - ./notebooks:/app/notebooks
    environment:
      - SPARK_EXPECTATIONS_CONFIG_PATH=/app/notebooks/config
      - SPARK_EXPECTATIONS_LOG_LEVEL=DEBUG
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - spark-net
  mailpit:
    image: axllent/mailpit:latest
    container_name: se-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - spark-net
    volumes:
      - ./containers/certs/mailpit.crt:/certs/mailpit.crt:ro
      - ./containers/certs/mailpit.key:/certs/mailpit.key:ro
    command:
      [
        "--smtp", "0.0.0.0:1025",
        "--smtp-tls-cert", "/certs/mailpit.crt",
        "--smtp-tls-key", "/certs/mailpit.key",
        "--smtp-auth-accept-any"
      ]           
  kafka:
    build:
      context: ../
      dockerfile: containers/kafka/Dockerfile.kafka
    ports:
      - "9092:9092"
    networks:
      - spark-net
networks:
  spark-net:
    driver: bridge
