name: "Publish GitHub Pages Docs"
on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to pass to docs command. Format: 'v1.2.3'"
        required: false
jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # fetch all commits/branches, needed for publish docs
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
              3.10
              3.11
              3.12
          check-latest: true
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Install dependencies
        run: |
          export PATH=$PATH:$HOME/.local/bin
          make deploy_env_setup
      - name: Publish Docs
        run: make deploy-docs version=${{ github.event.inputs.version }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
